sudo: false
dist: trusty
language: node_js
node_js:
  - 7.4
script: npm run-script ci
cache:
  directories:
    - node_modules
    - $HOME/.electron
addons:
  apt:
    packages:
      - rpm
      - lintian
after_success:
  - lintian test/fixtures/hadron-app/dist/*.deb
